language: generic
os:
- osx
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc 
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
script:
- mkdir build
- cd build
- cmake .. && make
Contact GitHub API Training Shop Blog About
